# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator_service.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculator_service.proto',
  package='calculator.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x18\x63\x61lculator_service.proto\x12\x10\x63\x61lculator.proto\"X\n\x0e\x43omputeRequest\x12,\n\x08operator\x18\x01 \x01(\x0e\x32\x1a.calculator.proto.Operator\x12\x0b\n\x03lhs\x18\x02 \x01(\x01\x12\x0b\n\x03rhs\x18\x03 \x01(\x01\"!\n\x0f\x43omputeResponse\x12\x0e\n\x06result\x18\x01 \x01(\x01*7\n\x08Operator\x12\x07\n\x03\x41\x44\x44\x10\x00\x12\x07\n\x03SUB\x10\x01\x12\x07\n\x03MUL\x10\x02\x12\x07\n\x03\x44IV\x10\x03\x12\x07\n\x03POW\x10\x04\x32^\n\nCalculator\x12P\n\x07\x43ompute\x12 .calculator.proto.ComputeRequest\x1a!.calculator.proto.ComputeResponse\"\x00\x62\x06proto3'
)

_OPERATOR = _descriptor.EnumDescriptor(
  name='Operator',
  full_name='calculator.proto.Operator',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ADD', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUB', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MUL', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIV', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POW', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=171,
  serialized_end=226,
)
_sym_db.RegisterEnumDescriptor(_OPERATOR)

Operator = enum_type_wrapper.EnumTypeWrapper(_OPERATOR)
ADD = 0
SUB = 1
MUL = 2
DIV = 3
POW = 4



_COMPUTEREQUEST = _descriptor.Descriptor(
  name='ComputeRequest',
  full_name='calculator.proto.ComputeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operator', full_name='calculator.proto.ComputeRequest.operator', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lhs', full_name='calculator.proto.ComputeRequest.lhs', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rhs', full_name='calculator.proto.ComputeRequest.rhs', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=134,
)


_COMPUTERESPONSE = _descriptor.Descriptor(
  name='ComputeResponse',
  full_name='calculator.proto.ComputeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='calculator.proto.ComputeResponse.result', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=169,
)

_COMPUTEREQUEST.fields_by_name['operator'].enum_type = _OPERATOR
DESCRIPTOR.message_types_by_name['ComputeRequest'] = _COMPUTEREQUEST
DESCRIPTOR.message_types_by_name['ComputeResponse'] = _COMPUTERESPONSE
DESCRIPTOR.enum_types_by_name['Operator'] = _OPERATOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ComputeRequest = _reflection.GeneratedProtocolMessageType('ComputeRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMPUTEREQUEST,
  '__module__' : 'calculator_service_pb2'
  # @@protoc_insertion_point(class_scope:calculator.proto.ComputeRequest)
  })
_sym_db.RegisterMessage(ComputeRequest)

ComputeResponse = _reflection.GeneratedProtocolMessageType('ComputeResponse', (_message.Message,), {
  'DESCRIPTOR' : _COMPUTERESPONSE,
  '__module__' : 'calculator_service_pb2'
  # @@protoc_insertion_point(class_scope:calculator.proto.ComputeResponse)
  })
_sym_db.RegisterMessage(ComputeResponse)



_CALCULATOR = _descriptor.ServiceDescriptor(
  name='Calculator',
  full_name='calculator.proto.Calculator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=228,
  serialized_end=322,
  methods=[
  _descriptor.MethodDescriptor(
    name='Compute',
    full_name='calculator.proto.Calculator.Compute',
    index=0,
    containing_service=None,
    input_type=_COMPUTEREQUEST,
    output_type=_COMPUTERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATOR)

DESCRIPTOR.services_by_name['Calculator'] = _CALCULATOR

# @@protoc_insertion_point(module_scope)
