# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import calculator_service_pb2 as calculator__service__pb2


class CalculatorStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Compute = channel.unary_unary(
                '/calculator.proto.Calculator/Compute',
                request_serializer=calculator__service__pb2.ComputeRequest.SerializeToString,
                response_deserializer=calculator__service__pb2.ComputeResponse.FromString,
                )


class CalculatorServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Compute(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Compute': grpc.unary_unary_rpc_method_handler(
                    servicer.Compute,
                    request_deserializer=calculator__service__pb2.ComputeRequest.FromString,
                    response_serializer=calculator__service__pb2.ComputeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculator.proto.Calculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Calculator(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Compute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculator.proto.Calculator/Compute',
            calculator__service__pb2.ComputeRequest.SerializeToString,
            calculator__service__pb2.ComputeResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
