name: Docker

on:
  push:
      branches:
          - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: docker build
      run: docker build -t aiminders/cpp-grpc-demo:latest .

    - name: docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: docker push-logout
      run: |
        docker push aiminders/cpp-grpc-demo:latest
        docker logout
